@LiaBE_HostAddress = http://localhost:5007

GET {{LiaBE_HostAddress}}/items/
Accept: application/json

###

GET {{LiaBE_HostAddress}}/items/1
Accept: application/json

###

POST {{LiaBE_HostAddress}}/items
Content-Type: application/json

{
    "Body": "A new item"
}
